// project
export const ADD_PROJECT = 'ADD_PROJECT';
export const REQUEST_PROJECTS_PENDING = 'REQUEST_PROJECTS_PENDING';
export const REQUEST_PROJECTS_SUCCESS = 'REQUEST_PROJECTS_SUCCESS';
export const REQUEST_PROJECTS_FAILED = 'REQUEST_PROJECTS_FAILED';

// task
export const REQUEST_TASKS_PENDING = 'REQUEST_TASKS_PENDING';
export const REQUEST_TASKS_SUCCESS = 'REQUEST_TASKS_SUCCESS';
export const REQUEST_TASKS_FAILED = 'REQUEST_TASKS_FAILED';

export const ADD_TASK = 'ADD_TASK';
export const CHANGE_TASK_VALUE = 'CHANGE_TASK_VALUE';

// // date.js
// export const SET_CURRENT_DATE = 'SET_CURRENT_DATE';

// // schedule
// export const CHANGE_SCHEDULE_FORM = 'CHANGE_SCHEDULE_FORM';
// export const INIT_SCHEDULE_FORM = 'INIT_SCHEDULE_FORM';
// export const SET_SCHEDULE_MODAL = 'SET_SCHEDULE_MODAL';
// export const SET_SCHEDULES = 'SET_SCHEDULES';